# Acknowledgements {-}

I have had the great privilege to work with and be inspired by many people
during my PhD candidature. It has been a challenging and rewarding experience
and I would not have been able to get through it without the support of my
advisers, colleagues, friends and family. 

I am deeply grateful to my supervisors: Dianne Cook, Matthew Ritchie, and Paul
Harrison. Di has been instrumental in helping me grow as a researcher
and teacher; she has been patient and always full of interesting insights and 
enthusiasm for the practice of doing data analysis. I am sorry that I have not named any of my software after Australian animals. Matt is one of the kindest and most generous scientists I know, thank you for allowing me to be a part of your lab and for all of the lab lunches! Paul has been a great advocate for me and my work, thank you for getting down in the trenches and always being available to help when I nag you about technical difficulties I'm having. 

My PhD would have been very different if I did not have the chance to collaborate with and learn from Michael Lawrence. Thank you for hosting me at Genentech in San Francisco and pushing me to grow as a programmer and researcher. Likewise, I am thankful to have had the opportunity to work with Michael Love who has been an enthusiastic collaborator and supporter. Hopefully I can visit North Carolina soon!  

Thank you to my PhD committee: David Frazier, David Powell, and Farshid Vahid. I am lucky to be in such a supportive environment at Monash EBS, a big thank you to Gael Martin and Rob Hyndman for their advice and guidance during the PhD. 

I am thankful to be part of the broader R and Bioconductor communities. Special thanks to Ian Lyttle and Alicia Schep for answering all of my annoying questions and letting me contribute to the **vegawidget** package. I thank Earo Wang, Ursula Laa, Shian Su, and Nick Tierney for always being available for chats (but really most importantly coffee or snacks) about software development and visualisation. 

I would like to thank my colleagues Charity Law, Peter Hickey, and Saskia Freytag for their friendship and guidance on all things statistical during my thesis. I look forward to having a drink with you in person.

I would not have been able to make it through this PhD if not for the support
of friends and family. Thank you to the members of FCC, Casey, Clare, Cyrus, Joy and Margs, for always being a delight and making my sides hurt from laughter and fried chicken. Thank you Michael, Rachel, Robbie, Anna, LP, Laura, Saskia, Lan and Josh for making life more fun. A big thanks to my mum, dad and sister for always being supportive of my choices and listening to my complaints. Finally, thank you to my partner Joy for encouraging me to pursue a PhD and always believing in me, even when I don't believe in myself. I am a better person because of you and I am so happy I get to spend my life with you.



